// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Soti.MobiControl.Bdd.PublicApiTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("DeletePackageFromCatalog")]
    public partial class DeletePackageFromCatalogFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "DeletePackageFromCatalog.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "DeletePackageFromCatalog", "Deleteing Package from API", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 5
 #line 6
    testRunner.Given("I am a system administrator", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
    testRunner.Given("Package file is stored at \'\\\\storage\\\\qaShare\\\\BDD_IntegrationTests_Data\\\\Android" +
                    "PlusPackage.pcg\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "DeviceFamily",
                        "PackagePlatform",
                        "ReferenceId",
                        "PackageName",
                        "Version"});
            table1.AddRow(new string[] {
                        "AndroidPlus",
                        "Android",
                        "autogenerate refId1.{guid}",
                        "autogenerate Aplus1.{guid}",
                        "1.0"});
            table1.AddRow(new string[] {
                        "AndroidPlus",
                        "Android",
                        "refId1.{guid}",
                        "Aplus1.{guid}",
                        "2.0"});
            table1.AddRow(new string[] {
                        "AndroidPlus",
                        "All",
                        "autogenerate refId2.{guid}",
                        "autogenerate Aplus2.{guid}",
                        "3.0"});
            table1.AddRow(new string[] {
                        "WindowsDesktop",
                        "WindowsCE",
                        "autogenerate windowsref1.{guid}",
                        "autogenerate windows.{guid}",
                        "1.0"});
            table1.AddRow(new string[] {
                        "Printer",
                        "Printer",
                        "autogenerate PrinterRef1.{guid}",
                        "autogenerate Printer.{guid}",
                        "1.0"});
            table1.AddRow(new string[] {
                        "WindowsCE",
                        "WindowsMobileSmartPhone",
                        "autogenerate MobileRef1.{guid}",
                        "autogenerate Mobile.{guid}",
                        "1.0"});
#line 8
    testRunner.And("System has packages with properties as follows:", ((string)(null)), table1, "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Delete Selected Packages")]
        [NUnit.Framework.TestCaseAttribute("refId1.{guid}", "1.0", null)]
        [NUnit.Framework.TestCaseAttribute("PrinterRef1.{guid}", "1.0", null)]
        [NUnit.Framework.TestCaseAttribute("MobileRef1.{guid}", "1.0", null)]
        public virtual void DeleteSelectedPackages(string referenceId, string version, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Delete Selected Packages", exampleTags);
#line 18
this.ScenarioSetup(scenarioInfo);
#line 5
 this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "ReferenceId",
                        "Version"});
            table2.AddRow(new string[] {
                        string.Format("{0}", referenceId),
                        string.Format("{0}", version)});
#line 19
testRunner.When("I Delete Package with following properties", ((string)(null)), table2, "When ");
#line 23
testRunner.Then("Public API response is \'OK\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Deleting a Pacakage associated with Profile returns error")]
        public virtual void DeletingAPacakageAssociatedWithProfileReturnsError()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Deleting a Pacakage associated with Profile returns error", ((string[])(null)));
#line 32
this.ScenarioSetup(scenarioInfo);
#line 5
 this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "PackageName",
                        "Depends On"});
            table3.AddRow(new string[] {
                        "Aplus1.{guid}",
                        ""});
#line 33
testRunner.Given("I created a profile for a platfrom \'AndroidPlus\' with package payloads as follows" +
                    "", ((string)(null)), table3, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "ReferenceId",
                        "Version"});
            table4.AddRow(new string[] {
                        "refId1.{guid}",
                        "1.0"});
#line 36
 testRunner.When("I Delete Package with following properties", ((string)(null)), table4, "When ");
#line 39
 testRunner.Then("Public API response is \'errorCode:1605\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Deleting only one version of Package")]
        public virtual void DeletingOnlyOneVersionOfPackage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Deleting only one version of Package", ((string[])(null)));
#line 42
this.ScenarioSetup(scenarioInfo);
#line 5
 this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "ReferenceId",
                        "Version"});
            table5.AddRow(new string[] {
                        "refId1.{guid}",
                        "1.0"});
#line 43
testRunner.Given("I Delete Package with following properties", ((string)(null)), table5, "Given ");
#line 46
 testRunner.When("I make a call to public API to get package summary for a package with reference I" +
                    "D refId1.{guid}", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "TotalVersions"});
            table6.AddRow(new string[] {
                        "Aplus1.{guid}",
                        "1"});
#line 47
 testRunner.Then("Resulting response contains information as follows:", ((string)(null)), table6, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
